import {
  LayoutDashboard,
  FileSpreadsheet,
  LogOut,
  Bell,
  Search,
  Filter,
  Plus,
  MoreVertical,
  CheckCircle,
  Clock,
  AlertCircle,
  Upload,
  Bot,
  Loader2,
  Trash2,
  Edit2,
  ChevronLeft,
  ChevronRight,
  Menu,
  X,
  User,
  Sun,
  Moon,
  Save
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Excel: FileSpreadsheet,
  Logout: LogOut,
  Bell: Bell,
  Search: Search,
  Filter: Filter,
  Plus: Plus,
  More: MoreVertical,
  Check: CheckCircle,
  Clock: Clock,
  Alert: AlertCircle,
  Upload: Upload,
  AI: Bot,
  Spinner: Loader2,
  Trash: Trash2,
  Edit: Edit2,
  Left: ChevronLeft,
  Right: ChevronRight,
  Menu: Menu,
  Close: X,
  User: User,
  Sun: Sun,
  Moon: Moon,
  Save: Save
};